feat: retry on telegram timeout exception
krddevdays/bot pull request #27
Opened 2024-06-01 14:01 UTC by brunql

2024-06-02 10:58 UTC, TyVik commented
Разработчики python-telegram-bot уже обсуждали эту проблему https://github.com/python-telegram-bot/python-telegram-bot/issues/354#issuecomment-1328091591 и выделили интерфейс BaseRequest, который можно переопределить. Сейчас python-telegram-bot использует httpx как его реализацию, а там можно подключить стратегию ретраев:
```
retry_strategy = httpx.Retry(
    total=3,  # Total number of retries (including the initial request)
    status_forcelist=[500, 502, 503, 504],  # HTTP status codes to retry
    backoff_factor=0.5,  # Factor by which the delay increases after each retry
    method_whitelist=["GET"],  # HTTP methods to retry
)
```

2024-06-02 18:48 UTC, TyVik requested changes

2024-06-03 09:35 UTC, brunql commented
> Сейчас python-telegram-bot использует httpx как его реализацию, а там можно подключить стратегию ретраев:
> 
> ```
> retry_strategy = httpx.Retry(
>     total=3,  # Total number of retries (including the initial request)
>     status_forcelist=[500, 502, 503, 504],  # HTTP status codes to retry
>     backoff_factor=0.5,  # Factor by which the delay increases after each retry
>     method_whitelist=["GET"],  # HTTP methods to retry
> )
> ```

Этот код есть только в одной статье, написанной каким-то идусом через ChatGPT:
https://scrapeops.io/python-web-scraping-playbook/python-httpx-retry-failed-requests/

В httpx нет такого API:
https://www.python-httpx.org/api/

Есть такой вариант:
https://www.python-httpx.org/advanced/transports/


```
import httpx
transport = httpx.HTTPTransport(retries=1)
client = httpx.Client(transport=transport)
```

Только на AsyncHTTPTransport заменить.

Если нужен функционал по retry из urllib3 тогда нужно писать BaseRequest на ее основе.

2024-06-03 09:38 UTC, brunql commented on krddevbot/__main__.py
> +    application = application.read_timeout(settings.BOT_READ_WRITE_TIMEOUT_SECONDS)
Приходит ошибка с таймаутом - самое первое и простое решение которое приходит в голову - увеличить таймаут, но сделать это настраиваемым через ENV. Какие тут нужны тести и рефакторинг не очень понял.

2024-06-03 09:40 UTC, brunql commented on krddevbot/message_api.py
> +    return await context.bot.send_message(**kwargs)
По оборачиванию методов согласен, каждый вызов придется оборачивать, не очень удобная история.

2024-06-04 14:10 UTC, TyVik commented on krddevbot/__main__.py
> +    application = application.read_timeout(settings.BOT_READ_WRITE_TIMEOUT_SECONDS)
А смысл тогда от таймаута? Его задача как раз определить, что внешний ресурс недоступен. И при этом по-максимуму не тормозить весь остальной поток управления. Так что увеличение таймаута скорей избегание проблемы, чем её решение.

2024-06-04 14:20 UTC, TyVik commented
Ха-ха, попался на бред ЧатГПТ :) Да, у httpx retry policy нет. Ну и фиг с ним, количества повторов должно быть достаточно. Можно действительно только транспорт AsyncHTTPTransport переопределить.

2024-06-09 09:18 UTC, closed without merging