28.09.24
krddevdays/bot pull request #31
Opened 2024-09-28 13:29 UTC by fokinkostya

Добавлено удаление сообщений до прохода бота. Объединены обработчики для входящих сообщений. Добавлена блокировка по "авито". Добавлены обработчики для команд /help, /rules, /list.

2024-10-06 14:23 UTC, TyVik requested changes

2024-10-06 14:23 UTC, TyVik commented on krddevbot/antispam/antispam.py
> +
Нет пустой строки

2024-10-06 14:23 UTC, TyVik commented on krddevbot/messages/__init__.py
> +    if update.message and context.user_data.get('joined', False):
У нас есть глобальный словарь `CHECKING_MEMBERS`, куда складываются `f"{user.id}_{chat.id}_{sent_msg.id}"`. Можно по вхождению в него подстроки `f"{user.id}_{chat.id}"` понимать проходит ли сейчас пользователь капчу или нет. И тогда флажок joined станет не нужным.

2024-10-06 14:23 UTC, TyVik commented on krddevbot/antispam/constance.py
> +HELP_MESSAGE_TEMPLATE = """/help - вызов справки
Между константами должна быть одна пустая строка.

2024-10-06 14:23 UTC, TyVik commented on krddevbot/messages/__init__.py
> +            await update.message.reply_text("WOW! Стоит прикупить лотерейный билет, с такой удачей. До встречи через сутки.")
Это задумывалось как шутка, так что с сутками, наверно, всё-таки перебор.

Давай оставим 5 минут и полчаса? Можно, кстати, обыграть DnD тематику типа https://rgbstudios.org/projects/dnd-dice?m=. Бросать 4d20 писать в чате "Пользователь %s призвал Авито. Спас-бросок 4d20: 1+1+1+1. Промах! Бан на полчаса.".

2024-10-06 14:23 UTC, TyVik commented on krddevbot/messages/__init__.py
> +        await days_without_mention(update=update, context=context)
Вот на самом деле avito, tander, antispam и пр. я хотел сделать подключаемыми модулями. Т.е. при старте приложения оно определяет из переменных окружения какие включены и подключает соответствующие обработчики. Хочется иметь возможность быстро отключать какую-то фичу, если она надоест.

Но я понимаю, что это уже несколько сложнее, так что не буду душнить и сделаю сам. Предлагаю направить этот PR в ветку commands -> я его волью (после вышеперечисленных правок) -> сам перетасую подключение обработчиков.

2024-10-06 14:24 UTC, TyVik commented on krddevbot/messages/__init__.py
> +        await days_without_mention(update=update, context=context)
А, я сам смог перенаправить. Так что этот тред больше для информации.

2024-10-06 14:31 UTC, fokinkostya commented on krddevbot/messages/__init__.py
> +    if update.message and context.user_data.get('joined', False):
Ок. Ранее спрашивал, ты дал направление побаловаться с context, отсюда и такое решение.

2024-10-06 15:23 UTC, fokinkostya commented on krddevbot/antispam/antispam.py
> +
Вроде есть или куда-то не туда гляжу? Файл оканчивается пустой строкой.

2024-10-06 15:23 UTC, fokinkostya commented on krddevbot/antispam/constance.py
> +HELP_MESSAGE_TEMPLATE = """/help - вызов справки
Добавил.

2024-10-06 15:24 UTC, fokinkostya commented on krddevbot/messages/__init__.py
> +            await update.message.reply_text("WOW! Стоит прикупить лотерейный билет, с такой удачей. До встречи через сутки.")
Переделал.

2024-10-06 15:43 UTC, fokinkostya commented on krddevbot/messages/__init__.py
> +    if update.message and context.user_data.get('joined', False):
Переделал.

2024-10-06 16:49 UTC, fokinkostya commented on krddevbot/messages/__init__.py
> +        await days_without_mention(update=update, context=context)
Ты хочешь что-то типа:
`ENABLED_MESSAGE_MODULES = 'avito,tander,antispam'`
и далее подцеплять перечисленное?
`enabled_message_modules = os.getenv("ENABLED_MESSAGE_MODULES").split(",")

messages_dir = Path("messages")

for module_name in enabled_message_modules:
    module_file = messages_dir / f"{module_name}.py"
    if module_file.exists():
        from messages import module_name as message_module
        message_handler_name = f"{module_name}_message_handler"
        if hasattr(message_module, message_handler_name):
            message_handler = getattr(message_module, message_handler_name)
            application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, message_handler, False))`

2024-10-12 13:43 UTC, TyVik commented on krddevbot/messages/__init__.py
> +        await days_without_mention(update=update, context=context)
Да, типа такого, но я ещё сам не определился как именно. Представленный вариант слишком захардкоженный... Но опять же, ещё не думал над реализаций.

2024-10-12 13:45 UTC, TyVik commented on krddevbot/messages/__init__.py
> +            await update.message.reply_text(f"Пользователь {lucky_user} призвал Авито. Спас-бросок 4d20: {result4d20}. Промах! Бан на пол часа.")
4d20 - 4 броска 20-гранного кубика. т.е. значения от 4 до 80. Вот если выпало минимальное, то это считается критичным промахом. У нас за такое бан.

Но я сам переделаю, тут недолго.

2024-10-12 13:54 UTC, TyVik approved these changes

2024-10-23 18:04 UTC, merged